
project_id = "gfhcmeicnbccihtyclbj"

[functions.create-buckets]
verify_jwt = false

[functions.notify-admin]
verify_jwt = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
