// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfhcmeicnbccihtyclbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmaGNtZWljbmJjY2lodHljbGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTcxMjcsImV4cCI6MjA2MDIzMzEyN30.bBOyUaigDzOtmIAgGB_bUzzyzwSWPLgi-n15UWsSRro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);